# Generated by Django 5.2.1 on 2025-05-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('E', 'Expense'), ('I', 'Income')], db_index=True, help_text='‘E’ for Expense, ‘I’ for Income', max_length=1)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('grocery', 'Grocery'), ('transport', 'Transport'), ('dining', 'Dining'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('subscriptions', 'Subscriptions'), ('insurance', 'Insurance'), ('misc', 'Misc'), ('salary', 'Salary'), ('bonus', 'Bonus'), ('gift', 'Gift'), ('dividends_interest', 'Dividends/Interest'), ('other', 'Other')], db_index=True, help_text='Pick one of the predefined categories', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
